kind: pipeline
name: default
type: docker

trigger:
  event:
    exclude:
      - promote

steps:
  - name: Install and Build
    image: node:17-alpine3.14
    commands:
      - yarn install
      - yarn build