kind: pipeline
name: default
type: docker

trigger:
  event:
    exclude:
      - promote

steps:
  - name: Install
    image: node:16-alpine3.14
    commands:
      - yarn install

  - name: Build
    image: node:16-alpine3.14
    commands:
      - yarn build
    depends_on:
      - Install

  - name: semantic-release
    image: stiforr/ci-tools:1
    pull: 'always'
    commands:
      - yarn semantic-release
    when:
      branch:
        - main
        - develop
      event:
        exclude:
          - pull_request
          - tag
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    depends_on:
      - Install
      - Build

---
kind: pipeline
name: publish
type: docker

trigger:
  event:
    include:
      - tag

steps:
  - name: docker
    image: plugins/docker
    environment:
      BUILDKIT_INLINE_CACHE: 1
      DOCKER_BUILDKIT: 1
      DATABASE_URL:
        from_secret: DATABASE_URL
    settings:
      cache_from: stiforr/minecraft-status-page
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: stiforr/minecraft-status-page
      build_args_from_env:
        - BUILDKIT_INLINE_CACHE
        - DATABASE_URL
      auto_tag: true
      tags:
        - latest