kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.persistentVolumeClaimName }}
spec:
  volumeName: database-pv-claim
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}